### PR TITLE
Improvement/policydescription

### PR DESCRIPTION
**Pull request by codytipton**
Fix policy description for consul.catalog.nodes_passing for accuracy

### CODE REVIEW

**Review by TheConnMan — CHANGES_REQUESTED** [review]
Could you update the release note in the History file? Otherwise LGTM.

**Comment by codytipton** [comment]
Thanks @TheConnMan. Version bumped.

**Comment by rclagett** [comment]
Version bump should happen when dev is merged to master. Changes made by this PR should be under Version next.

**Comment by codytipton** [comment]
@TheConnMan @rclagett 
version history was initially unchanged in this PR due to a mistake in previous PR 

https://github.com/netuitive-community-packages/netuitive-packages-linux-consul/pull/3

I had intended these PR's to be seperate, since they address seperate issues, but merged the release notes encompassing both changes in the former.

**Review by rclagett — APPROVED** [review]

**Review by yadima — APPROVED** [review]

**Pull request merged**
